### ISSUE TITLE
Is there any way to use Radish from plain python code?

### ISSUE THREAD

**Issue by eshansingh** [radish-bdd/radish#102]
Basically, is there a way to call radish from python scripts?

**Comment by timofurrer** [comment]
radish has no Python API which you can use to run your tests. Theoretically you could import `radish.main` and call the `main()` function. However, this functions assume a valid command line in `sys.argv` which is used by docopt internally.

I don't recommend this - instead use Python's `subprocess` module.

**Comment by eshansingh** [comment]
Do you think it's worth the effort for me to try and implement such an API?

**Comment by timofurrer** [comment]
I'm not sure. What would be the benefit over running radish as a subprocess?

**Comment by eshansingh** [comment]
Yeah, you're right. Thanks a lot!
