### ISSUE TITLE
Empty step pattern is giving "Cannot find step definition" when specified at the end of a step sentence

### ISSUE THREAD

**Issue by rscrimojr** [radish-bdd/radish#106]
I am using Python 2.7.10, MacOS Sierra version 10.12.4 and Radish-BDD version 0.4.1

With the feature file of:

```
Feature: A test feature for issues with tags specified after a scenario outline examples table
  A feature description here

  Scenario: Fruit Consumption 2
    Given I have a appple
    When I eat the apple
    Then I get lots of fiber
```
steps.py contents:
```
from radish import given, when, then


@given('I have a {}')
def my_step(step, fruit):
    pass


@when('I {} the {}')
def my_step(step, method, fruit):
    pass


@then('I get lots of {}')
def my_setp(step, what):
    pass
```

Then:
```
Error: Cannot find step definition for step 'Given I have a apple' in tests/stuff/features/stuff.feature:13

Error Oracle says:
There is no step defintion for 'Given I have a apple'.
All steps should be declared in a module located in tests/stuff.
For example you could do:

@step(r"Given I have a apple")
def my_step(step):
    raise NotImplementedError("This step is not implemented yet")
```

A workaround for using empty step patterns is (Adding something like a period or word after the `{}`):

NOTE: Your scenario sentences in your feature file will require adding the `.` or word to the end of the sentence also.

```
@step(r'I have a {}.')
def my_step(step, user):
    pass


@when(r'I {} the {}.')
def my_step(step, method, fruit):
    pass


@then(r'I get lots of {}.')
def my_step(step, what):
    pass
```

An alternative work-around is to use regexes as such:
```
import re

from radish import given, when, then


@given(re.compile(r'I have a (.+)'))
def my_step(step, fruit):
    pass


@when(re.compile(r'I (.+?) the (.+)'))
def my_step(step, method, fruit):
    pass


@then(re.compile(r'I get lots of (.+)'))
def my_step(step, what):
    pass
```

**Comment by rscrimojr** [comment]
Looking at the radish source code. In `matcher.py` I see that this may be a bug in the third-party library `parse`...

**Comment by timofurrer** [comment]
Interesting, looks indeed like a misbehavior in `parse`. I'll have a look at this, too and create an issue for parse if necessary.

**Comment by rscrimojr** [comment]
I have a fix to change `search` to `parse`. I cannot get the tests to run to verify... I can PR it if you want.

**Comment by timofurrer** [comment]
Yeah, just submit the PR and I have a look at it.

**Comment by timofurrer** [comment]
See #107

**Comment by timofurrer** [comment]
I've created an issue in the parse project: https://github.com/r1chardj0n3s/parse/issues/41

**Comment by timofurrer** [comment]
Update: https://github.com/r1chardj0n3s/parse/issues/41#issuecomment-299676040

**Comment by timofurrer** [comment]
Doesn't look to good. See: https://github.com/r1chardj0n3s/parse/issues/41#issuecomment-351587054

I think radish can't do anything either about this since the regex / pattern is ambiguous. 
If you want to match greedy in your example, please use a custom type:

```python
from radish import custom_type, given

@custom_type("GreedyMatcher", r"(.*)")
def greedy_matcher(text):
    return text

@given('I have a {:GreedyMatcher}')
def my_step(step, fruit):
    pass
```
