### ISSUE TITLE
.feature parsing: The number of spaces between keyword and colon matters

### ISSUE THREAD

**Issue by SamuelYvon** [radish-bdd/radish#118]
An example will be a little bit clearer:

> Scenario: Setup

and

> Scenario : Setup

are boot valid gherkins constructs. However, radish doesn't recognize the second one as a valid declaration. This is no big deal, but when you have multiple people writing scenarios, you don't always know how they are going to write it, and it fails silently. I suggest accepting both, as in some languages (french) the colon needs a space before.

**Comment by timofurrer** [comment]
That absolutely makes sense - I wasn't aware of that behavior.

I'll have a look at it asap.

**Comment by SamuelYvon** [comment]
I can make a PR when I fix the code, I know where it happens and it's a very simple fix

**Comment by timofurrer** [comment]
This issue was fixed with #121 :tada:
