### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#12]
**Supported languages:**

- [x] English
- [x] German
- [x] Portuguese
- [x] Spanish

**Comment by agb80** [comment]
What help do you need here? We could help with missing Spanish language

**Comment by timofurrer** [comment]
Yeah, spanish would be awesome and actually every additional language you
are able to translate to :)

**Comment by agb80** [comment]
Hope this PR is what you expected: https://github.com/radish-bdd/radish/pulls

**Comment by timofurrer** [comment]
Thanks :beers:
