### ISSUE TITLE
Support for boolean pattern

### ISSUE THREAD

**Issue by SamuelYvon** [radish-bdd/radish#132]
Hi!

Would it possible to have support for boolean pattern? such as true or false converts it to boolean in a step pattern?

For instance:

```
@given("This is {condition:B}")
def example(step, condition:bool):
    pass

```

I am more than willing to implement this if this is an acceptable feature!

**Comment by rscrimojr** [comment]
My 2 cents:

Is this something you can do with a radish `custom_type`?
e.g. 

```
import re
from radish import custom_type, register_custom_type, TypeBuilder

BOOL_PATTERN = re.compile(r'yes|y|true|t|1', flags=re.IGNORECASE)

@custom_type('Boolean', r'\s+')
def parse_boolean(text):
    return True if BOOL_PATTERN.search(text) else False

# register the boolean type
register_custom_type(Boolean=TypeBuilder.with_optional(parse_boolean)
```

**Comment by SamuelYvon** [comment]
Yes it would be possible to use a custom type, but imo a boolean is a pretty basic type and it would be a nice feature to have built-in. Of course, if @timofurrer thinks that boolean are not a worthy inclusion in radish, I will fallback to custom types.

**Comment by rscrimojr** [comment]
That sounds good.  I was just thinking that since the codes are the types supported by the `parse` / `parse_type` library, I thought that that would be something that maybe a candidate for a `custom_type`.  I am game, let's see what @timofurrer has to say about this.

**Comment by timofurrer** [comment]
I'd be willing to include such a custom type into radish. The only question is what would evaluate to `True` and what to `False`. How about upper and lower case etc? 

The other point is that I don't see why someone would want to have the word `true` or `false` in the step sentence (can you give some examples?). 
I just think that there are better ways to express a step in english than using `true` or `false` (and where it actually makes sense to convert those into bools)

**Comment by SamuelYvon** [comment]
Sorry totally forgot I opened this!

> Then I verify if the device 1 is registered expecting 1

Right now we use 1 or 0, and I agree that we could use is registered or is not registered, but it forces us to write two steps. 

We are trying to achieve a system where non-programmers can write features without having to touch the code, so if we duplicate everything it sorta becomes a mess, and having to write a different sentence is a bit more tedious (when you write features all day).

Now seeing the use case (I did not come up with it, I am just reporting it) I agree that it's not the most useful thing, but at the same time it is pretty easy (imo) to implement and if it makes some users happy I guess it's good!

Our use case here is probably different than what radish is aiming, so I would totally understand if you decide no to add this, I think otherwise I will add a custom parser.

I was thinking that true or false would be converted to a boolean in a case insensitive way. I think python does that by default already with `bool(str)`

**Comment by timofurrer** [comment]
> Now seeing the use case (I did not come up with it, I am just reporting it) I agree that it's not the most useful thing, but at the same time it is pretty easy (imo) to implement and if it makes some users happy I guess it's good!

Okay, fair enough :)

> Right now we use 1 or 0, and I agree that we could use is registered or is not registered, but it forces us to write two steps.

It wouldn't require you two write to steps you can use a custom parser which matches either `registered` or `not registered` and converts it to a `bool` or `0`/`1` - whatever suits you best.
With that I think you go the most *behavior driven* way. You've got a clear understandable English sentence and as a step developer you still get the `bool` you wish to get.

> Our use case here is probably different than what radish is aiming, so I would totally understand if you decide no to add this, I think otherwise I will add a custom parser.

If it really is what you need I think I'll merge a PR with the custom type - which still leaves the question what it should interpret: `true`, `false`, `True`, `False`, `0`, `1`, `yes` or `no` etc. ?

> I was thinking that true or false would be converted to a boolean in a case insensitive way. I think python does that by default already with bool(str).

Actually, in Python 3 it doesn't:

```python
>>> bool('true')
True
>>> bool('false')
True
>>> 
```

**Comment by SamuelYvon** [comment]
> Actually, in Python 3 it doesn't:

>>> bool('true')
True
>>> bool('false')
True
>>> 

Hmm well then, I have some buggy code somewhere then! 

> If it really is what you need I think I'll merge a PR with the custom type - which still leaves the question what it should interpret: true, false, True, False, 0, 1, yes or no etc. ?

I would really only go for `true TRUE True false FALSE False `, really, any variants of true and false. 

And I agree about the custom parser, but writing a custom parser for all the variants where we want to check a situation with a binary outcome to have it closer to English is a little tedious, it's nothing impossible it's just gonna be a lot of troubles and a source of bugs that we don't really need. 

I'll be making a PR in the next days!

**Comment by timofurrer** [comment]
> Hmm well then, I have some buggy code somewhere then!

Ouups, that's unfortunate.

> And I agree about the custom parser, but writing a custom parser for all the variants where we want to check a situation with a binary outcome to have it closer to English is a little tedious, it's nothing impossible it's just gonna be a lot of troubles and a source of bugs that we don't really need.

If you have a lot more situations where you want to parse booleans than just `is registered` and `is not registered` then I agree it can be tedious - but maybe still a good option.

I've made the experience that you rather hide the complexity of your steps inside the step implementations than in the sentence. So, if the sentence becomes much more clearer with the more verbose `is registered` and `is not registered` than that's fine. You write and read step sentences so much more often than you write the step implementation..

> it's nothing impossible it's just gonna be a lot of troubles and a source of bugs that we don't really need.

That's exactly why we've implemented http://radish.readthedocs.io/en/latest/tutorial.html#testing-step-patterns - with that you can check if your step sentence really matches the step you'd like it to.

And don't get me wrong - I don't want to convince you of something you really don't want to do - I'm just sharing my opinion - maybe it can be of any use to you :)

> I'll be making a PR in the next days!

Cool :beers:

**Comment by timofurrer** [comment]
I've just added a simple example to the functional tests which does what you want to achieve in a simple way:

* Feature File: https://github.com/radish-bdd/radish/blob/master/tests/functional/custom_types/features/Basic.feature
* Step implementations: https://github.com/radish-bdd/radish/blob/master/tests/functional/custom_types/radish/basic_steps.py
* Custom types: https://github.com/radish-bdd/radish/blob/master/tests/functional/custom_types/radish/terrain.py#L25
* Tests: https://github.com/radish-bdd/radish/blob/master/tests/functional/custom_types/tests/basic.yml

**Comment by CutiePi** [comment]
Idea for custom  boolean?
@custom_type('boolean', r'(True|TRUE|true|yes|1)')
def is_plugged_in(text):
    return text.upper() in ['TRUE', 'YES', '1']

**Comment by timofurrer** [comment]
Well, that can be simplified a lot by using the `(?i)` flag I guess. But yeah, something along those lines would be the alternative for matching booleans. 

@SamuelYvon you are going the submit the PR, right?

**Comment by SamuelYvon** [comment]
Yes! Whenever I find the time ;) Probably tonight or tomorrow

**Comment by rscrimojr** [comment]
You should add `on` and `off` while you are at it.

**Comment by CutiePi** [comment]
I implemented that in my base project work everywhere simple enough.

```
@custom_type("B", r"(?i)(true|yes|1|on|false|no|0|off)")
def boolean_type(text):
    """
    This will transform the supported text in boolean
    :param text:
    :return:
    """
    return text.upper() in ['TRUE', 'YES', '1','ON']
```
