### ISSUE TITLE
Python 3.6 DeprecationWarning: Flags not at the start of the expression

### ISSUE THREAD

**Issue by davidghiurco** [radish-bdd/radish#133]
EDIT: 
Radish version: 0.6.2
OS environment: Latest Mac OS

Whenever I run radish under python 3.6  (as of June 14th, 2017) this warning is shown:

{python_installation_folder}/lib/python3.6/site-packages/radish/utils.py:157: DeprecationWarning: Flags not at the start of the expression ^(?i)and 
  return re.sub(r'^{0}'.format(pattern), replacement, string)

before test steps are executed. At first I thought the problem was with how my test steps are written, but it turns out Python 3.6 just doesn't like how method 'str_lreplace' in utils.py handles regex expressions. 

I'm a medium-skill level python developer and I'm not sure what to make of the warning as I'm not seeing a whole lot about it on google/ stackoverflow. 

Any tips?

**Comment by timofurrer** [comment]
Thanks for the issue report :beers: 

I've already fixed it and will release a new version of radish in a few seconds! Stay tuned :tada:
