### ISSUE TITLE
Support for string with white spaces 

### ISSUE THREAD

**Issue by CutiePi** [radish-bdd/radish#134]
### I'd like to send a string with white spaces in from the step :
<b>Example</b>
- Then I assert the value of this element with xpath {element_xpath:S} on browser {browser_name:S} is equal to this value {expected_value:S}
- Use case :     Then I assert the value of this element with xpath //*[@id="content"]/form[1]/label on browser chromie is equal to this value Mac is present and connected 

<b>This fails, is there a way to use white spaces in a string because it sees this "Mac is present and connected" as multiple entries when it is one</b>

 For the moment I've bypassed the issue by replacing the white spaces with ; "Mac;is;present;and;connected" and parsing in my code.

<b><i>Regards, 
Jasmin

I work at M3touchinc
With @SamuelYvon

**Comment by timofurrer** [comment]
As you can see here: http://radish.readthedocs.io/en/latest/tutorial.html#step-pattern `parse` does not support a *string* as you wish it would. 

I actually wasn't aware of that - I probably never had to parse a multi word string.
As a quick work around you can just use `regex steps` or write a custom type. 

For the long run I'm thinking about supporting a `String` custom type - but like in #132 I'm wondering what characters to support in a string. Some would expect everything, some only characters which might appear in an English sentence ... Do you have some input?

On the other hand to prevent confusion it might be best to let people implement their own custom types for their needs and maybe document some common use-cases (as your string use case) as recipes in the radish docs?

**Comment by CutiePi** [comment]
I use radish to test web application from the front-end to the back end with splinter(selenium) and python. I will have to validate a lot of string values that will take various forms.  So doing regex steps or  every time is not a viable solution. Especially because we want a tester to write features without having to think about  the code. Although, the custom type is interesting. Is it only per step or it can be implemented as a project wide type?


As for what to support in a string, I'd recommend everything that is supported in a Python 3.* string. The rest would be custom types or regex steps. 

I think the implementation of custom types is a good idea but a default case standard string support would be a great tool! ;)

**Comment by SamuelYvon** [comment]
> I'm wondering what characters to support in a string.

Maybe supporting multiple words strings in quotation, so we can support every character and make sure that it does not interfere with the rest of the steps text?

**Comment by timofurrer** [comment]
> Maybe supporting multiple words strings in quotation, so we can support every character and make sure that it does not interfere with the rest of the steps text?

When I started to read @CutiePi post I was thinking about just that. A custom type which basically allows everything within double quotes and returns only what's between the double quotes?

**Comment by CutiePi** [comment]
I like the idea.

**Comment by SamuelYvon** [comment]
Yeah that's exactly what I was thinking!

**Comment by timofurrer** [comment]
Okay, I'm going to work on it. I'll release it towards the weekend :beers:
