### ISSUE TITLE
@precondition tag in feature file throwing RecursionError maximum recursion depth exceeded when parsing Scenario from same feature file

### ISSUE THREAD

**Issue by davidghiurco** [radish-bdd/radish#135]
OS: macOS Sierra (10.12.5)
Python version: 3.5.1
radish-bdd version: 0.6.3

I am writing a feature file which would greatly benefit from the functionality of the @precondition scenario tag described in the documentation as follows:

"""
Feature: My Awesome Feature
In order to document
radish I write this feature.
@precondition
(SomeFeature.feature: An awesome Scenario)
Scenario: Do some crazy stuff
When I add the following users to the database
| Sheldon | Cooper |
Then I expect to have 1 user in the database
"""

I am writing a feature file (for example's sake, call it MyFeature.feature) as follows:
```
Feature: MyFeature
...
@tag1
Scenario: First Scenario
...
steps 1
...

@tag2
@precondition(Myfeature.feature: First Scenario)
Scenario: Second Scenario which depends on the executions of First Scenario
...
steps 2
...
```

When running radish on this feature file (from a bash script where $1 is the feature file name):
```
radish features/$1.feature --basedir src/steps/ --cucumber-json cucumber.json --write-steps-once
File "lib/python3.5/site-packages/radish/parser.py", line 177, in _parse_context
    return parse_context_func(line)
  File "lib/python3.5/site-packages/radish/parser.py", line 343, in _parse_step
    return self._parse_scenario(line)
  File "lib/python3.5/site-packages/radish/parser.py", line 250, in _parse_scenario
    scenario = self._parse_precondition(tag[1])
  File "lib/python3.5/site-packages/radish/parser.py", line 419, in _parse_precondition
    feature = self._core.parse_feature(feature_file, self._tag_expr)
  File "lib/python3.5/site-packages/radish/core.py", line 100, in parse_feature
    feature = featureparser.parse()
  File "lib/python3.5/site-packages/radish/parser.py", line 148, in parse
    result = self._parse_context(line)

RecursionError: maximum recursion depth exceeded while calling a Python object
```

And the stack trace repeats and blows up my terminal stdout until finally RecursionError is thrown and it exits

I can confirm that it is the parsing of the @precondition scenario which causes this error, since removing that scenario (or at least, removing the '@precondition' tag) resolves the error. NOTE: It is also necessary for @tag1 and @tag2 to be in the feature file as those tags need to be in the cucumber report which radish will output. I tried removing the @tag1 and @tag2 tags and nothing changed. 

However, on that note, are multiple tags supported for radish in feature files? I did not find an answer in the documentation, so I figure it's good to ask here. Please advise how I could fix this @precondition scenario

**Comment by timofurrer** [comment]
Thanks for the report!

I'll have a look at it asap. 

> However, on that note, are multiple tags supported for radish in feature files? I did not find an answer in the documentation, so I figure it's good to ask her

Yes, you can just stack them:

```cucumber
@tag1
@tag2
Feature: Foo
    Feature and Scenarios support stacking
    tags.

    @tag1
    @tag3
    Scenario: Bar
        ...
```

Just because I'm curious: do you know about [Backgrounds](http://radish.readthedocs.io/en/latest/tutorial.html#background)? Wouldn't they suit you better? Or don't you have the same *precondition*/*background* for every Scenario in this Feature?

**Comment by davidghiurco** [comment]
I am aware of Backgrounds however they simply do not meet my needs in this case for exactly the reason you stated. There is no background which would apply to every scenario.

Without disclosing any internal information about the software system I'm working on testing (honestly wish I could give you internal details, but I'm bound by non-disclosure agreements) I'll describe what I'd like to happen:

Myfeature.feature has scenarios which are intended to test the proper creation, processing, expiration, and deletion of events within a big software system that lives in the cloud.

The feature file must test proper creation (1 scenario) and expiration and proper cleanup (another scenario) of an event.

More specifically,

Myfeature.feature looks like this
```
Feature: My Feature

@create
Scenario: New event created
Given a new event with some specific data must be created
And the event age is 20 minutes old
When the event is sent to the cloud server
Then the server creates the event with the expected type
And the event contains the expected data
And the event is created within a specified threshold time limit

@expire
@precondition(Myfeature.feature: New event created)
Scenario: Expire - event
When the event's age surpasses 30 minutes
Then the event expires and is removed from the system

@create
Scenario: New different type of event
...
steps
...

@expire
@precondition(Myfeature.feature: New different type of event)
Scenario: Expire - different type of event
...
steps 2
...
```

Etc. Now my concern is that the way I have this laid out right now would execute the @create Scenario then also execute the @create scenario again as a precondition to the @expire scenario, which would send 2 event messages up to the server, instead of just 1.

You might ask "Why don't you just merge the 2 scenarios?"
 The reason I do not have the @expire scenario steps as another 2 __then__ steps in the @create scenario is because the 2 scenarios represent 2 logically different aspects of the event processing system. (Also because my boss told me so, so there's not much flexibility there -_-)

I'm open to ideas about how to better design this, though.

**Comment by timofurrer** [comment]
> Without disclosing any internal information about the software system I'm working on testing (honestly wish I could give you internal details, but I'm bound by non-disclosure agreements)

No worries, that's fine :)

> Etc. Now my concern is that the way I have this laid out right now would execute the @create Scenario then also execute the @create scenario again as a precondition to the @Expire scenario, which would send 2 event messages up to the server, instead of just 1.

Yes, right know it would execute all the Scenarios and the `@create` ones twice - once standalone and once as precondition. However, you could prevent this by just specifying the [Tags](http://radish.readthedocs.io/en/latest/commandline.html#run-specify-certain-features-and-or-scenarios-by-tags) you want to run, which in your case would be the `@expire` ones.

> Furthermore, I'd like the @Expire scenario to only be run if its precondition @create scenario succeeds, otherwise skip it and do the other scenarios.

That's the default behavior for preconditions.

> I'm open to ideas about how to better design this, though.

At the moment I don't see another way - maybe due to the lack of information but maybe some ideas will pop up. I'll keep you posted.

**Comment by davidghiurco** [comment]
> Yes, right now it would execute all the Scenarios and the @create ones twice - once standalone and once as precondition. However, you could prevent this by just specifying the Tags you want to run, which in your case would be the @expire ones.

Is there a way to run scenarios by "all tags except ___" because not all scenarios I'm writing have the @create or @expire tags? And if there is, and say I run "all tags except @create" would @create be skipped in normal parsing but still be executed if it is a precondition? 

By the way, thanks for taking time to help me out. I really appreciate it.

**Comment by timofurrer** [comment]
> Is there a way to run scenarios by "all tags except ___" because not all scenarios I'm writing have the @create or @Expire tags? And if there is, and say I run "all tags except @create" would @create be skipped in normal parsing but still be executed if it is a precondition?

Yeah, of course there is. You can just say:

```bash
radish features/ --tags 'not create'
```

which would run all the Scenarios ***not** tagged with **create***.
Also have a look at the hints here:  http://radish.readthedocs.io/en/latest/tutorial.html#tags
And here https://github.com/timofurrer/tag-expressions - you can use all possible expressions allowed by *tag-expressions*.

> By the way, thanks for taking time to help me out. I really appreciate it.

You are very welcome :beers:

**Comment by davidghiurco** [comment]
> Yeah, of course there is. You can just say:
radish features/ --tags 'not create'

Oh okay I missed that part in the documentation. Would the excluded scenario still be executed as part of a pre-condition though?

**Comment by timofurrer** [comment]
> Oh okay I missed that part in the documentation. Would the excluded scenario still be executed as part of a pre-condition though?

That's a really good questions. I'm actually not sure about this. It definitely should - if it doesn't work it's a bug and we have to fix it.

Unfortunately, I don't have much time until the weekend - so this probably has to wait.

**Comment by davidghiurco** [comment]
> Unfortunately, I don't have much time until the weekend - so this probably has to wait.

That's totally fine. :)

**Comment by timofurrer** [comment]
Seems like I could provide a quick fix fairly easy. Could you test your feature against the current master?

**Comment by davidghiurco** [comment]
Seems that the RecursionError is fixed. However, I'm now having problems running just the @expire scenarios without having the @precondition scenarios executed standalone.... If i run the entire feature file, it seems to parse everything fine. However, if I say for example 'radish ... ... --tags 'expire' i.e. run only scenarios tagged with expire, then it says:

```
Error: Cannot import precondition scenario 'Precondition scenario description here' from feature 'features/MyFeature.feature': No such scenario

Error Oracle says:
You have a SyntaxError in your feature file!
Please have a look into the radish documentation to found out which
features radish supports and how you could use them:
Link: https://github.com/radish-bdd/radish
```

**Comment by timofurrer** [comment]
Yeah, I've completely forgot to address this issue as well. 
I'll have a look at it and hope to have a fix soon.

:beers:

**Comment by timofurrer** [comment]
Thanks to the new parser in the master branch, this is resolved. 
See integration tests:
* https://github.com/radish-bdd/radish/blob/master/tests/integration/features/Preconditions.feature#L102
* https://github.com/radish-bdd/radish/blob/master/tests/integration/features/Preconditions.feature#L140
