### ISSUE TITLE
Finish message shows test runtime in unintuitive format

### ISSUE THREAD

**Issue by davidghiurco** [radish-bdd/radish#138]
Radish version: 0.6.4
OS: Mac OS X 10.12 Sierra
Python: 3.5.1

Once tests are finished I get this output (this is true of any test I run, whether they are 1 feature with one scenario, or multiple features with multiple scenarios):

```
1 features (1 passed)
1 scenarios (1 passed)
9 steps (9 passed)
Run 1499105580 finished within 0.08333333333333333:5.194792 minutes
```

This test took about ~10 seconds (give or take). But you would not be able to know that from the values given above. Also I'm not sure where "1499105580" is coming from. It seems to be a random number whose presence has no real value being output.

I get output like this every time i run any radish test. 

This isn't a huge issue, just a formatting-for-human-readability kind of thing. Any suggestions about existing features which would make this look better? 

Or if they don't exist, might I suggest investigation into making this output a little more readable? :)

**Comment by timofurrer** [comment]
I've released **v0.6.6** which beautifies the duration output.

For example:
```
...
1 features (1 passed)
2 scenarios (2 passed)
9 steps (9 passed)
Run 1499274986 finished within a moment

...
1 features (1 passed)
2 scenarios (2 passed)
9 steps (9 passed)
Run 1499274971 finished within 2 seconds
```

It uses humanize.

:tada:

**Comment by davidghiurco** [comment]
thanks for the quick support 😄 🍻

**Comment by davidghiurco** [comment]
By the way, is there any rhyme or reason to the "Run 1499274986 finished within ..." 

What does that 1499274986 number mean?

**Comment by timofurrer** [comment]
I have to admit the documentation about it is not complete - there is no section in the Tutorial section - only in the Command Line Usage section.

http://radish.readthedocs.io/en/latest/commandline.html#run-use-custom-marker-to-uniquely-identify-test-run

It's a unique identifier for your test run.
