### ISSUE TITLE
Add coverage measurement

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#15]
Add coverage measurement to radish run (as plugin)

**Comment by timofurrer** [comment]
Fix coverage for specific packages.

**Comment by goodwillcoding** [comment]
If there is a bit more information on the expected output radish would generate for it I can try to look into this.

**Comment by timofurrer** [comment]
I want to have `coverage` integration like other test runners have. For example [nose](http://nose.readthedocs.io/en/latest/plugins/cover.html)

**Comment by timofurrer** [comment]
Some requirements I would like to have implemented:

- [ ] If no `--cover-packages` is given it should measure/report the coverage for all packages/modules involved from the user. Like the ones in the `--basedir` and the software under test.
- [ ] The radish package itself should not show up in the coverage report
- [ ] If `--cover-packages` is given only those packages should show up in the report

Features for next releases:

- [ ] Add `--cover-min-percentage` flag
- [ ] Add `--cover-html` flag to generate HTML report
- [ ] Add `--cover-branches` flag to measure branch coverage
- [ ] Add `--cover-config-file` flag to specify custom coveragerc location
- [ ] Add `--cover-erase` flag to erase previous collected coverage information.

**Comment by timofurrer** [comment]
All the above mentioned coverage options are implemented in #41
