### ISSUE TITLE
There is possibility to build radish test using existing tests?

### ISSUE THREAD

**Issue by Draqun** [radish-bdd/radish#165]
Hi.

I have a question. There is possibility to build test using smaller tests? eg.

Wait.feature
```
Feature: Some example feature:

    Scenario: Empty scenario
        When I am waiting idly
```

Bigger
```
Feature: Some bigger feature:

    Scenario: Wait 3 times
        Then Wait
```

If not there it is possible to do that?

PS. http://radish-bdd.io/ "Fork me on github" does not work. There is no link.

**Comment by timofurrer** [comment]
I'm not 100% sure what you want to achieve.
However, you can use Background or Scenario Preconditions.
Both are explained in the documentation.

**Comment by Draqun** [comment]
As I remember this is not what I want, but maybe I have to read about this deeply.

**Comment by timofurrer** [comment]
Can you elaborate on what you want exactly?

**Comment by Draqun** [comment]
We had idea of running radish tests from other radish test, but maybe we don't have to. I still talk about this with client.
