### ISSUE TITLE
Support running tests in parallel

### ISSUE THREAD

**Issue by fudomunro** [radish-bdd/radish#168]
We are using Radish to describe features executed by Selenium, and being able to run in parallel is essential for delivering results in a timely fashion.

I suspect a `--processes` argument to radish would probably be the correct interface for this.

I will investigate implementing this on my own, but if there's any other work out there to support this, I would love to hear about it.

**Comment by timofurrer** [comment]
I'd be open to review such a change in radish! Unfortunately, I cannot provide this implementation myself at this point of due to lack of time.

Thanks :beers:

**Comment by fudomunro** [comment]
Thanks. If I can pull it off in a nice, backwards-compatible way, I'll send you a PR.

**Comment by timofurrer** [comment]
Sounds great. I'm looking forward to it. Good luck! :four_leaf_clover:

**Comment by fudomunro** [comment]
Finally got a little time to dig into this, and here's where we are at:

We looked at changing how `runner.py` operates to separate collecting scenarios from running them. There may be other options.

Asyncio is not a good choice here, as really getting much benefit out of it would impose a lot on the step implementations.

Using actual processes or threads is probably the way to go, but there are definitely some complications to that. Besides actually moving data between threads, if we want to parallelize at the scenario level, then feature-level hooks might need to be run once for each thread, which could be cause problems for users, if they are, say, wiping a database during teardown after each feature. Doing it at the feature level probably would reduce the chance of a problem here, but reduces the benefits of running in parallel, as your longest feature would bottleneck the others.

We haven't totally abandoned that, but right now we are pursuing a different approach.

PyTest has a plugin for running in parallel, so we're investigating whether we could use PyTest as the actual runner. It would probably have some of the same complexities as using threads.

We are looking at other options as well, but so far we are very happy with Radish, so if we can make it work, that would be great.

**Comment by Vlaaaaaaad** [comment]
Threads for each scenario( including a thread for each scenario in Scenario Outlines! ) is also what https://github.com/grosser/parallel_tests is doing.

Since the idea behind having parallel tests is that you want to minimize the run time as much as possible, I think the complications are worth it. A switch between "_run a thread per scenario_" and "_run a thread per feature_" would be ideal( see `--group-by` in parallel_tests).

**Comment by timofurrer** [comment]
It certainly would be. Could you share it or some part of it? 

(I've already removed the `stale` tag :))

**Comment by timofurrer** [comment]
Sounds great! Keep me posted :tada:
