### ISSUE TITLE
No nested preconditions

### ISSUE THREAD

**Issue by vchernetsov** [radish-bdd/radish#172]
I suspect that nesting of preconditions is not fully working.
Here I have a agent.feature file where I want to have nested preconditions:

    Feature: Ability to manage agents
        Here I want to verify an ability to manage CRUD actions for agents by RESTful API

    @service
    Scenario: Declare person
        Given an object "person" with option ""

    @valid
    @precondition(agent.feature: Declare person)
    Scenario: Create valid invite
        When I create a resource "agent_service:invite" into context object "invite" with context data "person"
        Then check field "status_code" is "integer==201"

    @valid
    @precondition(agent.feature: Create valid invite)
    Scenario: Read valid invite
        When I read a resource "agent_service:invite" into context object "read_invite" by field "invite.suid"
        Then check field "status_code" is "integer==200"

When i run:

    root@06d20c1a2a54:/usr/src/app# radish radish/agent.feature
    Feature: Ability to manage agents  # radish/agent.feature
        Here I want to verify an ability to manage CRUD actions for agents by RESTful API

        @service
        Scenario: Declare person
            Given an object "person" with option ""

        @valid
        @precondition(agent.feature: Declare person)
        Scenario: Create valid invite
          As Precondition from agent.feature: Declare person
            Given an object "person" with option ""
          From Scenario
            When I create a resource "agent_service:invite" into context object "invite" with context data "person"
            Then check field "status_code" is "integer==201"

        @valid
        @precondition(agent.feature: Create valid invite)
        >>> this one is not proceed:
        Scenario: Read valid invite
          As Precondition from agent.feature: Create valid invite
            Given an object "person" with option ""

    1 features (0 passed)
    3 scenarios (2 passed)
    20 steps (11 passed)
    Run 1505819036 finished within a moment
    >>> this one is red:
    Error: The step 'Given an object "person" with option ""' does not have a step definition

But "show" command works just fine:

    root@06d20c1a2a54:/usr/src/app# radish show radish/agent.feature --expand
    Feature: Ability to manage agents  # radish/agent.feature
        Here I want to verify an ability to manage CRUD actions for agents by RESTful API

        @service
        Scenario: Declare person
            Given an object "person" with option ""

        @valid
        # @precondition(agent.feature: Declare person)
        Scenario: Create valid invite
            Given an object "person" with option ""
            When I create a resource "agent_service:invite" into context object "invite" with context data "person"
            Then check field "status_code" is "integer==201"

        @valid
        # @precondition(agent.feature: Create valid invite)
        Scenario: Read valid invite
            Given an object "person" with option ""
            When I create a resource "agent_service:invite" into context object "invite" with context data "person"
            Then check field "status_code" is "integer==201"
            When I read a resource "agent_service:invite" into context object "read_invite" by field "invite.suid"
            Then check field "status_code" is "integer==200"

**Comment by Cuauhtemoc-tzin** [comment]
can you show us the step definition of `Given an object person wityh option ""`

**Comment by vchernetsov** [comment]
No worries, I am using behave almost for a year.
