### ISSUE TITLE
Create an ability to use one scenario inside of another.

### ISSUE THREAD

**Issue by vchernetsov** [radish-bdd/radish#173]
You have a @precondition instruction which runs before scenario. Can we gave a similar instruction, named "scenario(FeatureFile.feature: My great scenario)" which can be ran inside of another scenario steps?

**Comment by timofurrer** [comment]
For now I want to stick to gherkin as much as possible without introducing other syntax which contradicts with the idea of BDD.

**Comment by timofurrer** [comment]
If you have really good reasons why radish should support that, I'll reopen.
