### ISSUE TITLE
A --quiet option

### ISSUE THREAD

**Issue by spmallette** [radish-bdd/radish#178]
It would be nice if there was a way to better control test outputs as they can be quite verbose. A `--quiet` option that disabled printing of all but failing scenarios would be quite helpful in this regard.

**Comment by timofurrer** [comment]
Sounds like a good idea.
What would you except as output for the Scenarios which do not fail?
Just print their sentences? Or do you except that `--quiet` just omits to print the step sentences?

**Comment by spmallette** [comment]
I think I would be happy if nothing printed at all for steps that do not fail. I'll just offer a little note about how I'm using radish so that you can perhaps understand what I tend to run into. I generally want to avoid scrolling up through a long list of passing scenarios to find the one that is amiss. I currently use the `-e` option which  helps, but when I add a lot of scenarios at once, that can be tedious as multiple failures can't be seen all at the same time. Then, and I admit that this is a problem probably specific mostly to me, but include the fact that I run radish (as well as my python build) through maven - our project is primarily java based - see http://tinkerpop.apache.com) and I get a mass of output that is really difficult to scroll through. 

I suppose you could get fancy with `--quiet` and offer differing levels of silence, but for my purposes I"m mostly interested in just seeing the fail situations, where seeing no fails means everything passed. I'd hope that the summary of pass/fail would not be lost with `--quiet` - that remains good information as confirmation of passing.

**Comment by timofurrer** [comment]
radish now has a `dots` formatter which can be used via the `-f dots` option.
See: https://radish.readthedocs.io/en/latest/commandline.html#run-dots-output-formatter

**Comment by timofurrer** [comment]
More formatters will follow in the next few weeks. 
I'm going to close this for now :tada:

**Comment by spmallette** [comment]
just tried this out. build logs are much more compacted. nicely done.   thanks
