### ISSUE TITLE
step text is null when I use scenario outline

### ISSUE THREAD

**Issue by cww1769** [radish-bdd/radish#208]
Hi, I found that when I use "scenario outline", step.text will be null. But step.text won'be be null if I use "scenario".

**Comment by timofurrer** [comment]
Can you provide a feature file to reproduce?

**Comment by cww1769** [comment]
please see the below feature, step.text is null in the second step.
///////////////////////////////////
Feature: Test dividing numbers
    In order to test the
    Scenario Outline features of
    radish I test dividing numbers.

    Scenario Outline: Divide Numbers
        Given I have the number <number1>
        And I have the text
            """
            hahaha
            """
        When I add them
        Then I expect the result to be <result>

    Examples:
        | number1 | result |
        | 10      | hahaha10   |
        | 6       | hahaha6    |
        | 24      | hahaha24      |

**Comment by timofurrer** [comment]
I've just merged a fix and it will be released with the up coming **v0.8.2** release.

Thanks for the bug report! 🍻
