### ISSUE TITLE
Gherkin reserverd words translation

### ISSUE THREAD

**Issue by agb80** [radish-bdd/radish#243]
It is possible to translate gherkin reserved words? I'm specially talking about Given/Then/When.

Currently we are working on a mixed language feature files in order to make it work with radish but would like to move into an standardized one.

**Comment by timofurrer** [comment]
> It is possible to translate gherkin reserved words?

For most of them it's already possible by specifying another language. However, it's unfortunately not yet possible for Given/When/Then.

The support for that seems to be pretty easy. I'll have a look at it tomorrow.

**Comment by timofurrer** [comment]
It seems to be more complex than I've initially thought. 

What I suggest you to do is to register the step with `@step()` and omit the keyword (Given/When/Then) or you write your own custom type, which accepts the keyword in the languages you want.

**Comment by agb80** [comment]
So sad, I was exiting about this, any way could you point me on the way to try the creation of my custom type?

**Comment by timofurrer** [comment]
You'll find the documentation here: https://radish.readthedocs.io/en/latest/tutorial.html#step-pattern

I'm going to close this for now, but I'll add it to my refactoring list.
