### ISSUE TITLE
How to read/set value from feature context

### ISSUE THREAD

**Issue by gmatesunny** [radish-bdd/radish#279]
In terrain.py I setup this

```
@before.each_feature
def init(feature):
    feature.context.delme = "UPANDDOWN"
```

Now in my steps of a scenario, I wanted to read this value. How I could do that. If I do 
```
@given ('Apple and orange')
def checkapple(step):
    print step.context.delme
```

It gives error AttributeError: 'Context' object has no attribute 'delme'

**Comment by timofurrer** [comment]
Each Feature has it's own context whereas a Scenario shares it's context with it's steps. 
The reason behind this is that a Scenario should be a standalone test case. It should be independent of the other Scenarios within the Feature. That's we they don't share the context. 

However, you can access the context of the Feature from a Scenario with `scenario.parent.context` and from a Step with `step.parent.parent.context`. You see that's a pretty ugly train wreck and you might want to re-think what you actually want to achieve with this. 
Why does the context have to be global within a Feature? Why not per Scenario? 
Is it just some global constant which you could put in the `world` object?

**Comment by timofurrer** [comment]
I'm going to close this for now. Let me know if there are still open questions.
