### ISSUE TITLE
latest radish-bdd version 0.9.0 is having issue

### ISSUE THREAD

**Issue by gowdatp** [radish-bdd/radish#287]
Issue while running radish : 

 File "/bin/radish", line 7, in <module>
from radish.main import main
File "/usr/lib/python2.7/site-packages/radish/main.py", line 13, in <module>
from .core import Core
File "/usr/lib/python2.7/site-packages/radish/core.py", line 10, in <module>
from .parser import FeatureParser
File "/usr/lib/python2.7/site-packages/radish/parser.py", line 360
)
^
SyntaxError: invalid syntax

Issue in code  :

in file : /usr/lib/python2.7/site-packages/radish/parser.py
line: 360 , there is a extra comma

scenario = scenario_type(
scenario_id,
*keywords,
sentence=detected_scenario,
path=self._featurefile,
line=self._current_line,
parent=self.feature,
tags=self._current_tags,
preconditions=self._current_preconditions,
background=background,    // Thos extra comma is to be removed.
)

**Comment by timofurrer** [comment]
I've released v0.9.1 which contains the bug fix. Unfortunately, this was introduced with formatting the code using black ... :tada:
