### ISSUE TITLE
Add support for skipping a step from inside the step

### ISSUE THREAD

**Issue by eerkunt** [radish-bdd/radish#295]
I dig up the documentation and the code itself and found out whenever 

```python
step.state = Step.State.SKIPPED
```

is set inside of any Step, due to 

https://github.com/radish-bdd/radish/blob/c80339f965ddd0a34834a43a54167cafe2e85f4b/radish/stepmodel.py#L124, `Step.State.SKIPPED` state is set as `Step.State.PASSED` on the next line and it is not possible to skip a step manually.

There might be some cases where a step (and the following steps) should be skipped, but not failed.

Is there a plan to add support for manually skipping any step ?

**Comment by dginther** [comment]
Oh fun! I love finding bugs in the upstream! 
Thanks for looking!
Great software you've got here, I love it.

**Comment by eerkunt** [comment]
Created a PR, but not sure if there is a better way to skip a step (or scenario ?) inside a step.

**Comment by eerkunt** [comment]
Thanks!

**Comment by eerkunt** [comment]
Hello @timofurrer,

Could you please release the new version ? 

By the way, the released radish-bdd version in PyPI is `0.9.1`, not even `0.9.2`.

**Comment by timofurrer** [comment]
Didn't have time yesterday, should be released now. Cheers 🎉
