### ISSUE TITLE
Consider using other yaml library than pyyaml

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#297]
PyYAML doesn't support unicode emoji characters, so they cannot be used within radish step test files.

Let's consider moving to another library which supports emojis.

**Comment by fliiiix** [comment]
At the moment it looks like https://pypi.org/project/ruamel.yaml/ is a string contender for a replacement.

**Comment by fliiiix** [comment]
Closed since they fixed it with pyyaml 5.1.
