### ISSUE TITLE
INFO: Drop Python 2.7 and Python 3.4 support

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#298]
Support for Python 2.7 will end with the beginning of 2020.  
Python 3.4 will get it's last update in a few months, march 2019.

I'll plan to drop Python 2.7 and Python 3.4 support in early summer 2019.
However, I'm happy to accept PRs for a Python 2.7 and Python 3.4 maintenance branch and I'll release accordingly.

**Comment by timofurrer** [comment]
Current master is Python 3 only! The first Python 3 only release will be **v1.0.0**.

**Comment by fliiiix** [comment]
Starting with the next release I will drop support for Python2.7 and Python3.4.
Python2.7 will not work anymore, Python3.4 might still work but is not supported.
Python3.5 is still tested and will still get some support for the next year or so as people are on stretch LTS with extended support.

https://github.com/radish-bdd/radish/pull/435

**Comment by fliiiix** [comment]
done witht tag v0.14.0
