### ISSUE TITLE
Documentation for "--profile"

### ISSUE THREAD

**Issue by goodwillcoding** [radish-bdd/radish#30]
Is there any documentation for "--profile" option? So far can not find any use of it in code?

**Comment by timofurrer** [comment]
It's missing in the docs. I'll keep this issue open until I find time to document it properly.

In short:
It can be used to specify some kind of configuration for your tests. This configuration can be checked/used in the step/hook implementation.

**Comment by goodwillcoding** [comment]
if you drop a quick example here of that I am happy to clean it up and submit a docs PR.

**Comment by timofurrer** [comment]
For example in case were the software under test is a software controlling some hardware. 
The test might check if some sensors work as expected.

Now, you want to use this very test to test the SUT against real hardware and against a simulation/emulation. So, in the feature file itself there is no change - However your step implementation and/or hooks have to know about the situation (real hardware vs. simulation).

For that you could set the `--profile` to `--profile=simulation` and act upon it in the step implementation / hook implementation.

Does that make sense?

**Comment by goodwillcoding** [comment]
I should clarify my question. I think I understand the concept. What is not clear where the profile variable is stored (for example `step.profile`)?

**Comment by goodwillcoding** [comment]
Okie, I see now it is on the threadlocal of the world object. I understand now. If you do not mind I'll try to submit a docs PR documenting "world" a little more

**Comment by timofurrer** [comment]
> Okie, I see now it is on the threadlocal of the world object

Exactly, all the arguments are attached to `world.conf` here: https://github.com/radish-bdd/radish/blob/master/radish/main.py#L30

> If you do not mind I'll try to submit a docs PR documenting "world" a little more

Of course not! I'm more than happy about every contribution :beers:

**Comment by goodwillcoding** [comment]
I addressed this #37

**Comment by timofurrer** [comment]
I've merged #37. Thus, I'll close this for now. :tada:
