### ISSUE TITLE
Radish does not include change made in Radish-BDD

### ISSUE THREAD

**Issue by anthonycolon25** [radish-bdd/radish#317]
Hi,
This is more of a question.  I am trying to work with terraform-compliance on a Windows machine. terraform-compliance requires radish and radish-bdd.  My radish version is 0.1.10 and radish-bdd is 0.11.1.

I am getting the following error:

OSError: Location 'c' to load modules does not exist error.

I found this [radish-bdd/radish@2723dbf](https://github.com/radish-bdd/radish/commit/2723dbfe77bf219ce232101bb568bd938a342fe8)
and made the changes to the radish/utils.py on my local machine and I no longer get the
OSError: Location 'c' to load modules does not exist error.

This is what I changed:

separator = ";" if os.name == "nt" else ":"
return list(x for x in itertools.chain(*(x.split(separator) for x in basedirs)) if x)
# return list(x for x in itertools.chain(*(x.split(":") for x in basedirs)) if x)

So it looks like the 0.1.10 radish version works fine on Linux but not on Windows because of the : separator.

My question is, has radish been merged into radish-bdd so they should not require radish any longer?  The merged pull request was only updated on radish-bdd/radish and not on radish itself (which is still 0.1.10).

**Comment by timofurrer** [comment]
I'm pretty confused here, so I need some clarification.

When you refer to *radish* you are talking about https://pypi.org/project/radish/, right?
Because that project has nothing todo with *radish-bdd*, which is this project :)

The changes from https://github.com/radish-bdd/radish/commit/2723dbfe77bf219ce232101bb568bd938a342fe8 are not in any release yet. I'll do one asap, though!

Cheers 🎉

**Comment by anthonycolon25** [comment]
Okay, Sorry for the confusion on the projects.  So the changes needed appear to be just for radish-bdd and will be released soon.

Thanks.

**Comment by timofurrer** [comment]
I've just release [v0.12.0](https://github.com/radish-bdd/radish/releases/tag/v0.12.0)

Have fun! :tada:
