### ISSUE TITLE
Refactor console writer

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#357]
The console writer has some unstructured weird shit in it. Let's refactor that a little.
Make clear in the writer what's indented, for what reason.

**Comment by eerkunt** [comment]
Hmm, can this also be related with #359 ?

**Comment by timofurrer** [comment]
Well, not really, I guess. This issue is for a planned refactoring while #359 seems to be a bug in certain environments.

**Comment by eerkunt** [comment]
Oh sorry for creating noise on this Issue then.
