### ISSUE TITLE
Support jUnit XML properties

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#384]
Support jUnit XML properties in the already existing extension. 
The properties should origin from the Feature Description like:

```gherkin
Feature: XML Properties
    This is arbitrary text and shouldn't be treated as
    a property. Even with a colon in it.

    Property A: foo
    Property B: bla
```

Also see #387

**Comment by fliiiix** [comment]
since this would allow only on set per feature for all scenarios lets opt for adding the tags to the specific `testcase` as properties

**Comment by fliiiix** [comment]
kinda fixed with https://github.com/radish-bdd/radish/pull/451
