### ISSUE TITLE
Issue in initializing values in terrain.py in radish and later using it in steps py files. 

### ISSUE THREAD

**Issue by rajvar2607** [radish-bdd/radish#390]
```python
@before.all
def before_all(features, marker):
    for feature in features:
        feature.context.detect_context_hostname = DETECT_CONTEXT_HOSTNAME
        feature.context.module_data_manager = MODULE_DATA_MANAGER_HOSTNAME
        feature.context.prtocol = PROTOCOL
```

I have initialized values as shown above in terrain.py. Later I want to use these values like "feature.context.detect_context_hostname" in some other stps.py function  like 

```python
@when("I sum them")
def sum_numbers(step):
    step.context.result = add(step.context.number1, step.context.number2)
    print(feature.context.prtocol)
```

.But it is not working and getting below error.
AttributeError: module 'radish.feature' has no attribute 'context'

If someone can help here. May be the way I am doing it is not correct.

**Comment by timofurrer** [comment]
Could you use the `@before.each_feature` hook and use the context there, to check if that's working?

```python
@before.each_feature
def setup_feature(feature):
    feature.context.detect_context_hostname = DETECT_CONTEXT_HOSTNAME
    feature.context.module_data_manager = MODULE_DATA_MANAGER_HOSTNAME
    feature.context.prtocol = PROTOCOL
```

which version of radish are you using?

**Comment by rajvar2607** [comment]
Hi, 
Thanks for your comment.

I am having radish-bdd 0.13.1

I can use before.each feature but i just want to initialize them just at the start of the execution of my whole test case package so wanted use before all tag.

**Comment by timofurrer** [comment]
In your case that seems to be fine. However, usually using `before_all` can lead to dependencies of the execution order - which is bad.

**Comment by rajvar2607** [comment]
ok
