### ISSUE TITLE
Import `each_scenario` fails

### ISSUE THREAD

**Issue by dschiller** [radish-bdd/radish#396]
I am trying to execute this Example: ```https://radish.readthedocs.io/en/latest/usage.html#implementing-hooks```

```
from radish import each_scenario
```

fails with

```
 cannot import name 'each_scenario' from 'radish' (c:\program files\python37\lib\site-packages\radish\__init__.py)
```

```
radish==0.1.10
radish-bdd==0.13.1
```

**Comment by timofurrer** [comment]
The `latest` docs are for the current master which is only released as `pre` version.
So please use the `stable` version on read the docs: https://radish.readthedocs.io/en/stable/tutorial.html

**Comment by timofurrer** [comment]
Or you could also be brave and use the `pre` release of radish - which I'll try to release at the end of this summer.
I'll have time to keep working on this in June.

**Comment by dschiller** [comment]
Thanks a lot Timo!
