### ISSUE TITLE
allow indicate several folders for look for features files and implementation steps

### ISSUE THREAD

**Issue by agb80** [radish-bdd/radish#40]
We are starting using radish to test a modular application; and the scenario is as follow.

We have 3 folders named _account_, _stock_, and _stock_account_. First two are self explained and the third one, the _stock_account_ is a folder that contains glue code for cover the cases where both modules (_account_ and _stock_ are being used).

The point is, to prevent repeat ourselvers, all scenarios on module _stock_account_ must use scenarios from _account_ and from _stock_ modules, but as the modules are on different forlders, radish doesn't know how to find them when runs. For now we are going to make a simbolic link on our test environments but will be great if the feature could be native on radish.

**Comment by timofurrer** [comment]
Sounds like you want to be able to specify multiple `--basedir / -b`, is that right?

As you know, radish does not support this at the moment.
What you can though in the meantime without having symlinks is to create your radish modules (`step.py`, `terrain.py`) in the `--basedir` and just import the modules from the desired folders like *stock* and *account*. Are those python packages? And are those in your `PYTHONPATH` / `sys.path`?

Good to hear that you decided to go with radish! If you have anything urgent regarding support please leave your comment in the gitter room.

**Comment by agb80** [comment]
Sorry for not being able to get back to you before; our folders are not python packages but there are on python path.

The suggestion of import the folders from other folders is working pretty well, maybe there is not need to indicate several folders after all.

**Comment by timofurrer** [comment]
> The suggestion of import the folders from other folders is working pretty well, maybe there is not need to indicate several folders after all.

So, how is it working with the import? Do you still need to have multiple base dirs?

**Comment by agb80** [comment]
Yes it's working very well as our modules are in python path even there are not python modules.

If you would like to close this issue is ok for me. Thanks a lot for your great work!

**Comment by timofurrer** [comment]
Cool :tada: 

So, I'm going to close this issue then.
