### ISSUE TITLE
Is it possible to restart a Scenario if one Step failed ?

### ISSUE THREAD

**Issue by dschiller** [radish-bdd/radish#406]
I have a Scenario where one Step may fail from time to time. I catch that Error and want to restart the Scenario in that case. Is that possible ?

Thank's a lot!

**Comment by timofurrer** [comment]
No, there is no such thing. I'd recommend to wrap radish into a script of some sort and re-trigger the run if it was unsuccessful.

**Comment by dschiller** [comment]
Hey Timo, was thinking about that. Thanks!
