### ISSUE TITLE
--cover-show-missing causes TypeError

### ISSUE THREAD

**Issue by katherine-walker** [radish-bdd/radish#411]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/radish-bdd/radish/blob/master/.github/CONTRIBUTING.md

[x] I have read and respect the code of conduct at https://github.com/radish-bdd/radish/blob/master/.github/CODE_OF_CONDUCT.md

[x] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
When running `radish-test matches x.yml --cover-show-missing -b y/`, I receive `TypeError: write() argument must be str, not ColorfulString`. I was able to bypass this error by removing `colorful` from the code inside of [this](https://github.com/radish-bdd/radish/blob/v0.13.3/radish/testing/matches.py#L138) conditional. I tried passing `--no-ansi`, but I just received the `radish-test` help info.

**Environment and Version**
* OS (incl. terminal and shell used): MacOS 10.15.8
* Python Version: 3.8.1
* radish Version (`radish --version`): 0.13.3

**To Reproduce**
A clear and concise description of steps to reproduce the behavior
you are experiencing.
This might also include a minimal Feature File and Step Implementations.
Write a `step-matches.yml` file that is missing a step from your `steps.py` file. Run `radish-test matches step-matches.yml --cover-show-missing` and receive a `TypeError`.

**Expected behavior**
I expected to not receive a `TypeError` or to be able to pass `--no-ansi` to avoid the `TypeError`.

**Comment by fliiiix** [comment]
Thanks for reporting. This will be in the next release! Let us know if you still experiencing any issues.
