### ISSUE TITLE
cucumber report "repeated keyword"

### ISSUE THREAD

**Issue by eudescosta** [radish-bdd/radish#422]
Hello all, 

So when using the cucumber-html-reporter (https://github.com/gkushang/cucumber-html-reporter) I get "duplicated" reference to the keyword, as you can see below...

![Screenshot 2021-08-03 at 12 17 38](https://user-images.githubusercontent.com/1360784/127999624-dc458588-32ff-46dd-9214-2cd8898986bc.png)

Looking at their source code here https://github.com/gkushang/cucumber-html-reporter/blob/develop/test/report/multi/cucumber_report-1.json you can see that the "name" attribute does not contain the keyword.

BTW, I could not find a json sample from the cucumber.io so I am assuming cucumber-html-reported is using the official cucumber formatting.

In radish, the handling of this field is done here https://github.com/radish-bdd/radish/blob/1685a48cacd491114cb6fb7e1dc3e1a54e8821a5/src/radish/extensions/cucumber_json_writer.py#L112

So I guess step.name comes with the keyword appended.

![Screenshot 2021-08-03 at 12 15 52](https://user-images.githubusercontent.com/1360784/127999515-ef9417c3-2de7-47d2-8bb1-3be71eabdc9c.png)

Would it be the case to strip out the keyword from the step.name?

**Comment by fliiiix** [comment]
@eudescosta is this still relevant for you? otherwise i would close this issue since i have no idea what the correct behavior should be

**Comment by fliiiix** [comment]
feel free to reopen
