### ISSUE TITLE
Support config file

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#45]
Support of a config file for the radish arguments.

**Comment by agb80** [comment]
I would like to suggest use the _setup.cfg_ file with a section named _radish_ seems to me will be easy to implement and is a common practice for many python tools.

**Comment by timofurrer** [comment]
`setup.cfg` seems reasonable if your radish settings are always for a particular setuptools-based project. But what if you want to specify some user-global settings? Or some for an arbitrary git-tree?

The thing I'm struggling with at the moment is how to implement this in a clean way with *docopt*. There is no way to find out whether the user specified the default value or if it actually is the default value -> in this case the config value would be taken.

**Comment by agb80** [comment]
One of the most flexible ways to manage configurations that I have found on a python projet is the one used by isort. Whit isort you have up to 4 ways to setup your configurations:

1. Create a ~/.isort.cfg file for setup your user-global settings
2. Create a .isort.cfg file  at the root of your project
3. Create an isort section to your project's setup.cfg
4. Create an .editorconfig file under the *.py section

You can take a look at how isort manage configuration here: https://github.com/timothycrosley/isort/blob/develop/isort/settings.py

**Comment by timofurrer** [comment]
Looks good to me! Thanks :beers: 

However, we have to figure out a good way to integrate it into *docopt* first - before starting the implementation.
