### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by bobotzzz** [radish-bdd/radish#450]
http://radish-bdd.io is not working
![image](https://user-images.githubusercontent.com/4257977/218470759-a8c5558a-0756-4906-89cf-230073388785.png)

**Comment by fliiiix** [comment]
Thanks for reporting let me talk to @timofurrer what happend there

**Comment by timofurrer** [comment]
Thanks for reporting.

These have been uncovered cost for many years and I'm not willing to pay for it - I've changed the URLs in the docs etc to point to https://radish-bdd.github.io which uses GitHub pages without a custom domain.

Sorry for the inconveniences this not-so-smooth switch caused :)
