### ISSUE TITLE
Add better support for flask/django

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#5]
Add a better support for web frameworks. Start with integrating flask

**Comment by vmesel** [comment]
What should be done to get a Flask integration?

**Comment by timofurrer** [comment]
I'm not sure about this. It would certainly need some investigation and proposals about what'd be useful to improve the experience when testing flask applications with radish.

Do you have anything in mind?

**Comment by tangorboyz** [comment]
For django mybe add `RadishTestRunner` and add it in django settings, custom command, with `python manage.py radish`
