### ISSUE TITLE
Support radish on windows

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#50]
The main features of radish should be supported on windows.

First we have to analyze where the gaps are. 
@SamuelYvon volunteered to contribute some of the windows support. 

I suggest to track the status of windows support with this issue.

**Comment by timofurrer** [comment]
- [ ] Add continuous integration for windows

**Comment by SamuelYvon** [comment]
Added a log file writer in PR #56. It replaced the syslog feature of linux/mac but also supports said platforms and windows.

**Comment by fliiiix** [comment]
All tests on windows run successful 
https://dev.azure.com/radish-bdd/radish/_build/latest?definitionId=1&branchName=master

If you have issues on windows please open a new Issue!
