### ISSUE TITLE
Highlight placeholders in ScenarioOutline

### ISSUE THREAD

**Issue by timofurrer** [radish-bdd/radish#60]
Visually highlight the placeholders in a ScenarioOutline.
Placeholders are everything between the `<` and `>` for which a column exists in the examples.

The implementation should go into the `console_writer` extension.

**Comment by rscrimojr** [comment]
@timofurrer Are you okay with `<placeholder>` being highlighted? Not just the placeholder name between the <>?

**Comment by timofurrer** [comment]
Yes, that would be okay, too!

Are you working on this?

**Comment by rscrimojr** [comment]
Yes,  I have a solution that I will PR today.

**Comment by timofurrer** [comment]
Sounds great :tada:
