### ISSUE TITLE
behave_like cannot find step definition

### ISSUE THREAD

**Issue by sschelm** [radish-bdd/radish#79]
radish 0.3.2
python 3.6.0
Mac OS 10.11.6

I tested the `step.behave_like()` command by copying a step definition and only replacing the definition part at the beginning with the above command.
For the two step definitions I tried this with I get the following error:
`StepDefinitionNotFoundError: Cannot find step definition for step ...`
These steps work just fine on their own in other tests.

I wonder if this might have the same root cause as the issue #61 with the 'And' chaining ...

**Comment by timofurrer** [comment]
Can you please provide the feature file and your step definitions where this error occurs?

I've justed pushed a functional tests for the `step.behave_like()` feature here: https://github.com/radish-bdd/radish/tree/master/tests/functional/behave_like

> I wonder if this might have the same root cause as the issue #61 with the 'And' chaining ...

I can't tell without more information.

**Comment by sschelm** [comment]
The attached files create the error:
`Given I am logged in
          StepDefinitionNotFoundError: Cannot find step definition for step 'I click New User Access Profile' in features/login_behave_issue_feature.txt:5`
This step is not actually needed for the login but the following `behave_like()` commands in the login step behave the same and you can see the step definition for the initial error (New User Access Profile) right below the login step.
I had to replace the actual URL and the admin credentials but I can reproduce the error with the attached files nonetheless.

[login_behave_issue_feature.txt](https://github.com/radish-bdd/radish/files/913099/login_behave_issue_feature.txt)

[step_behave_issue_py.txt](https://github.com/radish-bdd/radish/files/913114/step_behave_issue_py.txt)

**Comment by timofurrer** [comment]
Well, it's kind of related to #61 but not really. 
The error is that you are using `@when()` to register your step which means that the step pattern is prefixed with the *When*, thus the step sentence of  `click_new_user` is registered as `When I click New User Access Profile` which means you also have to use it in `step.behave_like()` like that:

```python
step.behave_like('When I click New User Access Profile')
```

It's actually intended behavior if you use the `@when()` decorator. #61 aims to provide the functionality **only** when using in combination with `And`. So, it would match the following steps correctly:

```gherkin
When I lick the login button
And I click New User Access Profile
```

**Comment by sschelm** [comment]
Ah, yes.
I changed the behave calls and it works.

It might be a worthwhile to expand the tutorial parts of behave to make this more clear...?

**Comment by timofurrer** [comment]
> It might be a worthwhile to expand the tutorial parts of behave to make this more clear...?

I'll do that as soon as I find some time to do that. If you have some I'm always happy to review PRs!

Cheers :beers:
