### ISSUE TITLE
How to generate html report?

### ISSUE THREAD

**Issue by miraculixx** [radish-bdd/radish#90]
Is there a recommended tool/script to conusme the cucumber json or bdd xml produced by radish?

**Comment by timofurrer** [comment]
radish doesn't provide any built-in way to generate HTML for either of them.

However, for cucumber JSON there is [cucmber-html-report](https://github.com/leinonen/cucumber-html-report) which creates HTML files for your cucumber json files.

I doubt that a similar thing exist for the BDD XML. You'd have to parse it yourself and create a HTML report.

**Comment by timofurrer** [comment]
Because this was rather a usage question than an actual issue - I'm going to close this! 

Thanks :tada:
